### ISSUE TITLE
App name issue

### ISSUE THREAD

**Issue by faveoled** [flathub/io.gitlab.coolreader_ng.crqt-ng#21]
![image](https://github.com/flathub/io.gitlab.coolreader_ng.crqt-ng/assets/85760289/b2d3e97e-8c61-497d-a0a2-7d8a8d728563)
Flatpak name is too technical now

**Comment by virxkane** [comment]
I think this would be wrong. I believe the name of the flatpak package should be the same as the name of the program. At the moment I have no plans to change the name of the program.

**Comment by faveoled** [comment]
![image](https://github.com/flathub/io.gitlab.coolreader_ng.crqt-ng/assets/85760289/fbf1d08f-88dc-493c-8016-5ff7eb50cd22)
Exactly. That is the name of the program

**Comment by virxkane** [comment]
I agree that there is some confusion with the name of the program, but the correct name of the program is indicated in the [README.md](https://gitlab.com/coolreader-ng/crqt-ng/-/blob/main/README.md?ref_type=heads).

Later I will try to eliminate this inaccuracy.

Thanks.

**Comment by virxkane** [comment]
The application name has been changed in the upstream. CoolReaderNG is no longer mentioned.
